# Generated by Django 2.2.1 on 2019-06-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(max_length=200)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'journal',
            },
        ),
    ]
